runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
#api_version: 1
#threadsafe: true

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.appyy
