DROP SCHEMA IF EXISTS `CreditCardDefault` ;
CREATE SCHEMA IF NOT EXISTS `CreditCardDefault` 
CREATE TABLE IF NOT EXISTS `CreditCardDefault`.`credit_card_tbl` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `limit_bal` DOUBLE NULL DEFAULT NULL,
  `age` DOUBLE NULL DEFAULT NULL,
  `pay_1` INT(11) NULL DEFAULT NULL,
  `pay_2` INT(11) NULL DEFAULT NULL,
  `pay_3` INT(11) NULL DEFAULT NULL,
  `pay_4` INT(11) NULL DEFAULT NULL,
  `pay_5` INT(11) NULL DEFAULT NULL,
  `pay_6` INT(11) NULL DEFAULT NULL,
  `bill_amt1` DOUBLE NULL DEFAULT NULL,
  `bill_amt2` DOUBLE NULL DEFAULT NULL,
  `bill_amt3` DOUBLE NULL DEFAULT NULL,
  `bill_amt4` DOUBLE NULL DEFAULT NULL,
  `bill_amt5` DOUBLE NULL DEFAULT NULL,
  `bill_amt6` DOUBLE NULL DEFAULT NULL,
  `pay_amt1` DOUBLE NULL DEFAULT NULL,
  `pay_amt2` DOUBLE NULL DEFAULT NULL,
  `pay_amt3` DOUBLE NULL DEFAULT NULL,
  `pay_amt4` DOUBLE NULL DEFAULT NULL,
  `pay_amt5` DOUBLE NULL DEFAULT NULL,
  `pay_amt6` DOUBLE NULL DEFAULT NULL,
  `cc_default` INT(11) NULL DEFAULT NULL,
  `grad_school` INT(11) NULL DEFAULT NULL,
  `university` INT(11) NULL DEFAULT NULL,
  `high_school` INT(11) NULL DEFAULT NULL,
  `male` INT(11) NULL DEFAULT NULL,
  `married` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30001
DEFAULT CHARACTER SET = utf8